---
apiVersion: v1
kind: ConfigMap
metadata:
    name: odala-mt-earthquake-config
data:
    BROKER_URL: http://localhost:9090
    CKAN_URL: https://dati.toscana.it
    CKAN_DATASTORE_ID: 536efa03-31e1-4ed2-ae49-ed31905b26ea
    CKAN_API_KEY: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx